package org.SinjabPracAutomation.Enums;

public enum DemoQAEnums {

    URL , FIRST_NAME, LAST_NAME, EMAIL,  PHONE_NUMBER, DATE_OF_BIRTH, SUBJECT, GENDER_MALE, SPORTS,
    UPLOAD_PICTURE, CURRENT_ADDRESS, SELECT_CITY, SELECT_STATE, SUBMIT_BTN
}
