package org.SinjabPracAutomation.Enums;

public enum WebEnums {

    URL ,  EMAIL, PASSWORD,SIGN_IN, CLUB_MANAGEMENT, PACKAGE_MENU, CREATE_PACKAGE, BRANCH_DROPDOWN, SELECT_SPORTS,
    EXPIRY_MONTHDROPDOWN, PACKAGE_CATEGORY, PACKAGE_TYPE, PACKAGE_ENGTITLE, PACKAGE_ARBTITLE,PACKAGE_DESENG,PACKAGE_DESARB,
    PACKAGE_DURATION,PACKAGE_PRICE, PACKAGE_USAGECOUNT, PACKAGE_BOOKINGDISCOUNT, PACKAGE_DRAFTBTN
}
