package org.SinjabPracAutomation.Enums;

public enum WebEnums {

    URL , FIRST_NAME, LAST_NAME, EMAIL, PASSWORD,SIGN_IN, PHONE_NUMBER, DATE_OF_BIRTH, SUBJECT, GENDER_MALE, SPORTS,
    UPLOAD_PICTURE, CURRENT_ADDRESS, SELECT_CITY, SELECT_STATE, SUBMIT_BTN
}
